(define-map conditional_refund_registry uint {creator: principal, data: (string-ascii 256), timestamp: uint})
(define-data-var conditional_refund_nonce uint u0)
(define-read-only (get-entry (id uint)) (map-get? conditional_refund_registry id))
(define-public (register (data (string-ascii 256)))
  (let ((id (+ (var-get conditional_refund_nonce) u1)))
    (map-set conditional_refund_registry id {creator: tx-sender, data: data, timestamp: stacks-block-height})
    (var-set conditional_refund_nonce id)
    (ok id)))
