(define-map confidential_auction_engine_registry uint {creator: principal, data: (string-ascii 256), timestamp: uint})
(define-data-var confidential_auction_engine_nonce uint u0)
(define-read-only (get-entry (id uint)) (map-get? confidential_auction_engine_registry id))
(define-public (register (data (string-ascii 256)))
  (let ((id (+ (var-get confidential_auction_engine_nonce) u1)))
    (map-set confidential_auction_engine_registry id {creator: tx-sender, data: data, timestamp: stacks-block-height})
    (var-set confidential_auction_engine_nonce id)
    (ok id)))
(define-public (update-entry (id uint) (data (string-ascii 256)))
  (let ((entry (unwrap! (map-get? confidential_auction_engine_registry id) (err u1))))
    (asserts! (is-eq tx-sender (get creator entry)) (err u2))
    (map-set confidential_auction_engine_registry id (merge entry {data: data}))
    (ok true)))
