(define-map escrow_vault_registry uint {creator: principal, data: (string-ascii 256), timestamp: uint})
(define-data-var escrow_vault_nonce uint u0)
(define-read-only (get-entry (id uint)) (map-get? escrow_vault_registry id))
(define-public (register (data (string-ascii 256)))
  (let ((id (+ (var-get escrow_vault_nonce) u1)))
    (map-set escrow_vault_registry id {creator: tx-sender, data: data, timestamp: stacks-block-height})
    (var-set escrow_vault_nonce id)
    (ok id)))
