(define-map subscription_liquidity_pool_registry uint {creator: principal, data: (string-ascii 256), timestamp: uint})
(define-data-var subscription_liquidity_pool_nonce uint u0)
(define-read-only (get-entry (id uint)) (map-get? subscription_liquidity_pool_registry id))
(define-public (register (data (string-ascii 256)))
  (let ((id (+ (var-get subscription_liquidity_pool_nonce) u1)))
    (map-set subscription_liquidity_pool_registry id {creator: tx-sender, data: data, timestamp: stacks-block-height})
    (var-set subscription_liquidity_pool_nonce id)
    (ok id)))
(define-public (update-entry (id uint) (data (string-ascii 256)))
  (let ((entry (unwrap! (map-get? subscription_liquidity_pool_registry id) (err u1))))
    (asserts! (is-eq tx-sender (get creator entry)) (err u2))
    (map-set subscription_liquidity_pool_registry id (merge entry {data: data}))
    (ok true)))
