(define-map supplier_performance_analysis_registry uint {creator: principal, data: (string-ascii 256), timestamp: uint})
(define-data-var supplier_performance_analysis_nonce uint u0)
(define-read-only (get-entry (id uint)) (map-get? supplier_performance_analysis_registry id))
(define-public (register (data (string-ascii 256)))
  (let ((id (+ (var-get supplier_performance_analysis_nonce) u1)))
    (map-set supplier_performance_analysis_registry id {creator: tx-sender, data: data, timestamp: stacks-block-height})
    (var-set supplier_performance_analysis_nonce id)
    (ok id)))
(define-public (update-entry (id uint) (data (string-ascii 256)))
  (let ((entry (unwrap! (map-get? supplier_performance_analysis_registry id) (err u1))))
    (asserts! (is-eq tx-sender (get creator entry)) (err u2))
    (map-set supplier_performance_analysis_registry id (merge entry {data: data}))
    (ok true)))
