(define-map data principal uint)
(define-data-var counter uint u0)
(define-read-only (get-data (key principal))
  (ok (default-to u0 (map-get? data key)))
)
(define-public (set-data (key principal) (value uint))
  (ok (begin
    (map-set data key value)
    (var-set counter (+ (var-get counter) u1))
    true
  ))
)
(define-public (increment)
  (ok (begin
    (var-set counter (+ (var-get counter) u1))
    (var-get counter)
  ))
)
(define-read-only (get-counter)
  (ok (var-get counter))
)
(define-public (process-value (val uint))
  (ok (+ val u1))
)
